service: aws-logs  

provider:
  name: aws
  runtime: nodejs4.3
  stage: prod  
  iamRoleStatements:
      - Effect: "Allow"
        Action: "logs:DescribeLogStreams"
        Resource: "*"    
      - Effect: "Allow"
        Action: "lambda:*"
        Resource: "*"    

functions:
  groups:
    handler: handler.groups
    events:
        - schedule: rate(15 minutes)
  streams:
    handler: handler.streams

plugins: 
  - serverless-run-function-plugin  

