service: aws-logs  

provider:
  name: aws
  runtime: nodejs4.3
  stage: prod  
  iamRoleStatements:
      - Effect: "Allow"
        Action: "logs:DescribeLogStreams"
        Resource: "*"    
      - Effect: "Allow"
        Action: "lambda:*"
        Resource: "*"    

custom:
  writeEnvVars:
    groups: ${env:LOG_GROUPS}

functions:
  groups:
    handler: handler.groups
  streams:
    handler: handler.streams

plugins: 
  - serverless-plugin-write-env-vars
  - serverless-run-function-plugin  

